language: "vi-VN"
tone_instructions: "Be concise and assertive. Get straight to the point. No pleasantries."
early_access: false
enable_free_tier: true

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: ""
  high_level_summary_in_walkthrough: true
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: ""
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: false
  estimate_code_review_effort: true
  assess_linked_issues: false
  related_issues: false
  related_prs: true
  suggested_labels: false
  labeling_instructions: []
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  in_progress_fortune: true
  poem: false
  path_filters:
    - "**/src/**"
    - "!**/.env*"
    - "!**/node_modules/**"
    - "!**/dist/**"  
  path_instructions: 
    - path: "**/src/**"
      instructions: |
        CRITICAL RULES:
        1. Cross-reference with CODING_STANDARDS.md for details
        2. Every violation MUST cite EXACT Rule ID from rules-index.json
        3. Format: "[RULE-ID] Rule Title: Vietnamese explanation"
        4. If no matching rule exists, describe issue WITHOUT using Rule ID format
        
        REQUIRED Citation Format:
        "[SEC-CRED-001] No Hard-coded Secrets: Secret phải dùng process.env.JWT_SECRET"
        "[TS-NAMING-007] Constants must be UPPER_SNAKE_CASE: Đổi bucketUpload thành BUCKET_UPLOAD"
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels:
      - coderabbit-review
    drafts: false
    base_branches:
      - develop
    ignore_usernames: []
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  pre_merge_checks:
    docstrings:
      mode: "off"
      threshold: 80
    title:
      mode: "error"
      requirements: "Title should start with a verb, be syntactically correct, and ideally be under 50 characters"
    description:
      mode: "off"
    issue_assessment:
      mode: "warning"
    custom_checks: []
  tools:
    ast-grep:
      rule_dirs:
        - rules
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: true
    ruff:
      enabled: false
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: "default"
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: false
    phpstan:
      enabled: false
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    golangci-lint:
      enabled: false
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: false
    eslint:
      enabled: true
    flake8:
      enabled: false
    rubocop:
      enabled: false
    buf:
      enabled: false
    regal:
      enabled: false
    actionlint:
      enabled: true
    pmd:
      enabled: false
    cppcheck:
      enabled: false
    semgrep:
      enabled: true
    circleci:
      enabled: true
    clippy:
      enabled: false
    sqlfluff: 
      enabled: false
    prismaLint:
      enabled: true
    pylint:
      enabled: false
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: false
    luacheck:
      enabled: true
    brakeman:
      enabled: false
    dotenvLint:
      enabled: true
    htmlhint:
      enabled: true
    checkmake:
      enabled: true
    osvScanner:
      enabled: true

chat:
  art: false
  auto_reply: true
  integrations: {}

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "rules-index.json"
      - "CODING_STANDARDS.md"
      - "**/.cursorrules"
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  pull_requests:
    scope: "auto"

code_generation:
  docstrings:
    language: en-US
  unit_tests:
    path_instructions: []